### PR TITLE
Developed About Us

### LINKED ISSUE #11: Developing About Us
About Page should contain cards which have pics, name and github profile link of contributor getting data dynamically from assets/content.md file and images from assets/images.

### PR DESCRIPTION
**Pull request by siddharthgoel94**
Developed the About Us page with the following features:
- Fetches data from the `content.md`  file in contribution directory 
- Displays the image of the contributor as well stored in images directory (the image should be named with the Github username of the contributor)
- If the image is not available in the directory then the Github avatar of the person is displayed on the page
- Also the link to the Github profile is added in the card

Fixes #11

### CODE REVIEW

**Comment by MoazamAli45** [comment]
That's great 👍 can you also add heading and search bar if possible. I am creating a new Issue. Thanks

**Comment by siddharthgoel94** [comment]
Thanks for merging the PR
I will add search bar functionality feature as well, You can assign me that issue

**Comment by MoazamAli45** [comment]
Sure. You can comment

**Comment by siddharthgoel94** [comment]
Hi @MoazamAli45 
I just checked out the deployment and found there is some issue fetching the content.md from the deployed site.
It's working fine in the local environment though
Currently I am thinking of fixing that issue first
You can assign the search bar issue to someone else if you want

Thank You

**Comment by MoazamAli45** [comment]
Sure you can resolve it

**Pull request merged**
