### PR TITLE
Improved quiz app by adding Validation and optimizing event listeners

### PR DESCRIPTION
**Pull request by kayashth1**
I fixed form validation to ensure proper input before submission, preventing incomplete data entries. I optimized the event listeners to avoid multiple triggers, ensuring smoother quiz functionality. I refactored the HTML to dynamically load questions through JavaScript, enhancing the flexibility and scalability of the quiz app.

### CODE REVIEW

**Comment by MoazamAli45** [comment]
@kayashth1  It is not working fine even I am not able to select any value

**Comment by kayashth1** [comment]
@MoazamAli45, I apologize for any inconvenience, but I have committed all changes and fixed the bugs; kindly check the pull request.

**Comment by MoazamAli45** [comment]
Now it is working fine thanks

**Comment by kayashth1** [comment]
@MoazamAli45 my pleasure.

**Pull request merged**
