### PR TITLE
improved user experience

### LINKED ISSUE #36: Improving User experience
in your website submit button is left and the prev button is on right actually for better user experience the submit button should be on right and the prev button should on left .

i would like to work on this issue under Hacktoberfest'24

Screenshot 2024-10-21 231335

after updating it would be look like this

image

### PR DESCRIPTION
**Pull request by Prudhvi-232**
fixes #36

### CODE REVIEW

**Comment by MoazamAli45** [comment]
Prev button size should also be same

**Comment by Prudhvi-232** [comment]
I will work on this

**Comment by Prudhvi-232** [comment]
Please check now. If any updates are required, kindly mention them, and I will make the necessary corrections.

**Comment by Prudhvi-232** [comment]
fixes both #36 and #26 
please check and close the PR, if any updates required, kindly mention them


https://github.com/user-attachments/assets/7843a83f-3ce9-4899-8372-23fcfc8e55fb

**Comment by Prudhvi-232** [comment]
could you please add the "hacktoberfest-accepted" label to this PR, as i am contributing under hacktoberfest as it would contribute to my efforts during Hacktoberfest.

**Pull request merged**
