### PR TITLE
Home Screen

### PR DESCRIPTION
**Pull request by Mukta64Chaudhari**
Added css and html file for homescreen.

### CODE REVIEW

**Comment by Mukta64Chaudhari** [comment]
I have comitted changes, please check

**Comment by MoazamAli45** [comment]
I mean you have to change the main UI in index.html file by adding navbar and footer. Navbar have two links home and about

**Comment by Mukta64Chaudhari** [comment]
Oh ok, I will make these changes.

**Comment by MoazamAli45** [comment]
Now you can take the updated pull as previous has conflicts. Now you can work on contact page. I  am making issue

**Pull request closed without merging**
