### PR TITLE
Enhance 'Contact Us' page styling and update contribution details

### LINKED ISSUE #29: Enhance Styling of Contact Us Page and Update to Contribution Details
### Description:
I would like to propose the following enhancements as part of my participation in Hacktoberfest and express my intention to work on this issue:

1. **Contact Us Page Styling**: I propose to enhance the styling of the "Contact Us" page to improve user experience and overall aesthetics. This will involve comprehensive adjustments to various aspects, including the layout, color scheme, typography, and design elements. The goal is to create a more visually appealing interface that aligns with modern design standards and ensures ease of navigation for users.

2. **Contribution Details Update**: Additionally, I would like to update my details in the `content.md` file located in the contribution folder. I inadvertently omitted this information in my last pull request, and I believe including it will provide clarity regarding my contributions to the project.

I am eager to work on these enhancements and contribute positively to the project.

Please let me know if any further information or clarification is required.

### PR DESCRIPTION
**Pull request by poshithNandyala**
resolves  #29
### 1. Enhanced "Contact Us" Page Styling:
- Improved the layout, color scheme, typography, and design elements to enhance the overall user experience.
- Added a placeholder to the input field for better user interaction.
- The new design ensures better navigation and aligns with modern design standards.

### 2. Fixed Mobile Responsiveness:
- Ensured that the "Contact Us" page is now fully responsive and looks good on smaller screens.
- Adjusted layout and styling using media queries to improve the user experience on mobile devices.

### 3. Updated Contribution Details:
- Added my details to the `content.md` file in the contribution folder, which were inadvertently omitted in the previous pull request.

## Screenshots

**Before:**
Screenshot 2024-10-19 122745

**After:**
image

---

I believe these updates will positively contribute to the project's UI/UX, improve mobile experience, and add clarity to the contribution history. Looking forward to your feedback!

### CODE REVIEW

**Comment by poshithNandyala** [comment]
I have updated the styling to ensure that the 'Contact Us' page now displays properly on mobile screens. The layout and elements have been optimized for responsiveness and should work smoothly across different screen sizes. Please review the changes and let me know if any further adjustments are needed

**Comment by MoazamAli45** [comment]
On mobile screen it should not have margin  enough that's why it is strecthing and also button is not looking good. Thanks

**Comment by poshithNandyala** [comment]
I have optimized the layout for mobile screens. Please review my changes and merge them when convenient.

**Comment by MoazamAli45** [comment]
Still not working fine

**Comment by poshithNandyala** [comment]
image
Can you specifically tell me what I can change in it? I think it is usable on mobile screens

**Comment by poshithNandyala** [comment]
Thank you for taking the time to review my pull request. I kindly request that you add the "hacktoberfest-accepted" label to this PR, as it would contribute to my efforts during Hacktoberfest.

Thank you for your support.

**Pull request merged**
